import { ThemeOption, WordPair } from './types';

export const THEMES: ThemeOption[] = [
  { id: 'argentina', label: 'Argentinidad al Palo', emoji: '🇦🇷' },
  { id: 'cordoba', label: 'Córdoba Básica', emoji: '🍷' },
  { id: 'memes_argentinos', label: 'Memes Argentinos', emoji: '🤣' },
  { id: 'farandula', label: 'Farándula & TV', emoji: '📺' },
  { id: 'comida', label: 'Comida de Bodegón', emoji: '🍕' },
  { id: 'futbol', label: 'Fútbol Pasión', emoji: '⚽' },
  { id: 'marcas', label: 'Marcas Nostalgia', emoji: '🏷️' },
  { id: 'musica', label: 'Rock & Cumbia', emoji: '🎸' },
  { id: 'lugares', label: 'Lugares & Viajes', emoji: '✈️' },
  { id: 'objetos', label: 'Cosas de la Casa', emoji: '🏠' },
  { id: 'mitos', label: 'Mitos y Leyendas', emoji: '🐉' },
  { id: 'scifi', label: 'Ciencia Ficción', emoji: '👽' },
  { id: 'religion', label: 'Religión & Creencias', emoji: '🙏' },
  { id: 'historia', label: 'Historia Argentina', emoji: '📜' },
];

export const WORD_LISTS: Record<string, WordPair[]> = {
  memes_argentinos: [
    // --- Personajes Icónicos ---
    { normal: 'Ricardo Fort', undercover: 'Chocolate' }, // Por la fábrica y el "Cortaste toda la looz"
    { normal: 'El Comandante', undercover: 'General' }, // Fort vs Rango militar real
    { normal: 'Samid', undercover: 'Mauro Viale' }, // "Usted se tiene que arrepentir" (ambos protagonistas)
    { normal: 'Atendedor de Boludos', undercover: 'Inspector de Línea' }, // Su "trabajo" real en el video
    { normal: 'El Gigoló', undercover: 'Estafador' }, // Personaje vs Lo que realmente era
    { normal: 'July3p', undercover: 'Youtuber' }, // Personaje vs Profesión
    { normal: 'El Bananero', undercover: 'Harry Potter' }, // Por el video "Harry el sucio Potter" o "Sape"
    { normal: 'Zulma Lobato', undercover: 'Vedette' }, // Personaje vs Profesión soñada
    { normal: 'La Chabona', undercover: 'Abogada' }, // Por su video viral con Burlando
    { normal: 'El Facha', undercover: 'Turro' }, // "Hola soy el Facha" vs Estilo

    // --- Frases y Momentos Virales ---
    { normal: 'Hermosa Mañana', undercover: 'Francella' }, // La frase vs El actor (ambos ríen)
    { normal: 'Alto Guiso', undercover: '15 Pesos' }, // El meme vs El precio original
    { normal: 'Y Candela?', undercover: 'La Moto' }, // La pregunta vs El objeto del choque
    { normal: 'Un Elissir', undercover: 'Blue Label' }, // Coco Basile vs La bebida
    { normal: 'Messirve', undercover: 'Pulgar Arriba' }, // La cara de Messi vs El gesto
    { normal: 'Andá pa allá bobo', undercover: 'Periodista' }, // A quién se lo dijo (Weghorst/Gastón Edul cerca)
    { normal: 'Traeme la Copa', undercover: 'Obelisco' }, // El pedido vs Donde se festeja
    { normal: 'Esto se va a descontrolar', undercover: 'Caída' }, // La frase vs Lo que pasa después
    { normal: 'Chinwenwencha', undercover: 'Sinvergüenza' }, // La pronunciación viral vs La palabra real
    { normal: 'Barassi', undercover: 'Raro' }, // El conductor vs Su frase icónica "Raaaro"

    // --- Selección y Fútbol (La Scaloneta) ---
    { normal: 'Dibu Martínez', undercover: 'Loco' }, // El arquero vs Su personalidad
    { normal: 'Abuela la la la', undercover: 'Festejo' }, // El personaje vs La acción
    { normal: 'Scaloneta', undercover: 'Ferrari' }, // El apodo vs Un auto rápido
    { normal: 'Papu Gómez', undercover: 'Beckham' }, // Por el stream donde se comparó

    // --- TV y Cultura Bizara ---
    { normal: 'Crónica TV', undercover: 'Placa Roja' }, // El canal vs Su elemento más famoso
    { normal: 'Okupas', undercover: 'Pollo' }, // La serie vs El personaje/comida
    { normal: 'Los Simuladores', undercover: 'Operativo' }, // La serie vs Lo que hacen
    { normal: 'Teto Medina', undercover: 'Humo' }, // Momentos bizarros vs Efecto
    { normal: 'Las Pastillas del Abuelo', undercover: 'Maradona' }, // Por la canción viralizada
    { normal: 'Pity Álvarez', undercover: 'Fuego' }, // Sus locuras vs Incendio

    // --- Actualidad "Memeable" ---
    { normal: 'Horno de Barro', undercover: 'Pizzero' }, // Por el meme de "Rompió el horno de barro"
    { normal: 'Mylazyan', undercover: 'Milanesa' }, // La pronunciación cheta vs La comida
    { normal: 'Nordelta', undercover: 'Carpincho' }, // El lugar vs Los invasores
    { normal: 'Fábrica de Pastas', undercover: 'Ñoqui' }, // Lugar real vs Empleado público (doble sentido)
    { normal: 'Trapito', undercover: 'Estacionamiento' }, // Personaje urbano vs Lugar
    { normal: 'Visto', undercover: 'Clavado' }, // WhatsApp vs Acción

    // --- Extras para completar ---
    { normal: 'AFIP', undercover: 'Ladrón' }, // Meme clásico argentino
    { normal: 'No es Coca Papi', undercover: 'Coca-Cola' }, // Frase viral
    { normal: 'Tinelli', undercover: 'Lunes' }, // Ambos molestos
    { normal: 'Batakis', undercover: 'Emoji' }, // Por el gif viral
    { normal: 'Galperin', undercover: 'Mercado Libre' }, // El dueño vs La empresa
    { normal: 'Manaos', undercover: 'Veneno' }, // Meme de la gaseosa
    { normal: 'El Diego', undercover: 'Dios' }, // Maradona el eterno
    { normal: 'Mirtha', undercover: 'Dinosaurio' }, // Meme de la longevidad
    { normal: 'Boca Juniors', undercover: 'Gallina' }, // Clásico insulto
    { normal: 'River Plate', undercover: 'Pato' }, // Clásico insulto
    { normal: 'Perón', undercover: 'Fantasma' }, // Siempre vuelve
    { normal: 'La Pesada', undercover: 'Mochila' }, // Algo que pesa
    { normal: 'Guarda con el Quemado', undercover: 'Limón' }, // Meme clásico
    { normal: 'Y Bueno', undercover: 'Dale' }, // Frases comodín argentinas
  ],
  mitos: [
    { normal: 'Drácula', undercover: 'Murciélago' },
    { normal: 'Hombre Lobo', undercover: 'Perro' },
    { normal: 'Sirena', undercover: 'Pescado' },
    { normal: 'Fantasma', undercover: 'Sábana' },
    { normal: 'Pombero', undercover: 'Duende' },
    { normal: 'Luz Mala', undercover: 'Linterna' },
    { normal: 'Nahuelito', undercover: 'Tronco' }, // Flota en el lago
    { normal: 'Extraterrestre', undercover: 'Turista' },
    { normal: 'Zombie', undercover: 'Borracho' }, // Caminan parecido
    { normal: 'Bruja', undercover: 'Suegra' }, // Clásico
    { normal: 'Hada', undercover: 'Mosquito' }, // Vuelan y son chicas
    { normal: 'Dragón', undercover: 'Dinosaurio' },
    { normal: 'Unicornio', undercover: 'Caballo' },
    { normal: 'Cíclope', undercover: 'Tuerto' },
    { normal: 'Minotauro', undercover: 'Vaca' },
    { normal: 'Medusa', undercover: 'Peluquera' }, // Por el pelo
    { normal: 'Fénix', undercover: 'Pollo' },
    { normal: 'Pie Grande', undercover: 'Gorila' },
    { normal: 'Momia', undercover: 'Herido' }, // Vendas
    { normal: 'Frankenstein', undercover: 'Robot' },
    { normal: 'Vampiro', undercover: 'Mosquito' }, // Chupan sangre
    { normal: 'Lobizón', undercover: 'Oveja' },
    { normal: 'La Llorona', undercover: 'Alarma' }, // Ruido molesto
    { normal: 'Gualicho', undercover: 'Receta' },
    { normal: 'Chupacabras', undercover: 'Perro' },
    { normal: 'Mago', undercover: 'Estafador' },
    { normal: 'Hechizo', undercover: 'Mentira' },
    { normal: 'Caldero', undercover: 'Olla' },
    { normal: 'Escoba', undercover: 'Aspiradora' },
    { normal: 'Cueva', undercover: 'Sótano' },
  ],
  scifi: [
    { normal: 'Ovni', undercover: 'Dron' },
    { normal: 'Alien', undercover: 'Extranjero' },
    { normal: 'Robot', undercover: 'Licuadora' },
    { normal: 'Nave Espacial', undercover: 'Avión' },
    { normal: 'Sable de Luz', undercover: 'Linterna' },
    { normal: 'Darth Vader', undercover: 'Asmático' }, // Respiración
    { normal: 'Yoda', undercover: 'Rana' },
    { normal: 'Terminator', undercover: 'Guardaespaldas' },
    { normal: 'Matrix', undercover: 'Internet' },
    { normal: 'Clon', undercover: 'Gemelo' },
    { normal: 'Viaje en el Tiempo', undercover: 'Historia' },
    { normal: 'Teletransportación', undercover: 'Colectivo' },
    { normal: 'Láser', undercover: 'Puntero' },
    { normal: 'Galaxia', undercover: 'Vía Láctea' },
    { normal: 'Agujero Negro', undercover: 'Bolsillo' }, // Donde va la plata
    { normal: 'Astronauta', undercover: 'Buzo' }, // Trajes parecidos
    { normal: 'Marte', undercover: 'Desierto' },
    { normal: 'Inteligencia Artificial', undercover: 'Google' },
    { normal: 'Cyborg', undercover: 'Prótesis' },
    { normal: 'Avatar', undercover: 'Pitufo' }, // Azules
    { normal: 'Chewbacca', undercover: 'Alfombra' },
    { normal: 'E.T.', undercover: 'Dedo' },
    { normal: 'Thanos', undercover: 'Guante' },
    { normal: 'Meteorito', undercover: 'Piedra' },
    { normal: 'Gravedad', undercover: 'Imán' },
    { normal: 'Cohete', undercover: 'Fuego Artificial' },
    { normal: 'Satélite', undercover: 'Espejo' },
    { normal: 'Mutante', undercover: 'Feo' },
    { normal: 'Superhéroe', undercover: 'Policía' },
    { normal: 'Villano', undercover: 'Político' },
  ],
  historia: [
    { normal: 'San Martín', undercover: 'Caballo Blanco' },
    { normal: 'Belgrano', undercover: 'Bandera' },
    { normal: 'Cabildo', undercover: 'Casita de Tucumán' }, // Confusión escolar
    { normal: 'Granaderos', undercover: 'Soldaditos' },
    { normal: 'Colón', undercover: 'Turista' },
    { normal: 'Virrey', undercover: 'Gobernador' },
    { normal: 'Escarapela', undercover: 'Pin' },
    { normal: 'Himno', undercover: 'Canción' },
    { normal: 'Sarmiento', undercover: 'Maestra' },
    { normal: 'Rosas', undercover: 'Espinas' },
    { normal: '1810', undercover: '1816' }, // Fechas patrias
    { normal: 'Cruce de los Andes', undercover: 'Excursión' },
    { normal: 'Carreta', undercover: 'Auto' },
    { normal: 'Vela', undercover: 'Foco' },
    { normal: 'Mazamorra', undercover: 'Arroz con Leche' },
    { normal: 'Damas Antiguas', undercover: 'Modelos' },
    { normal: 'Paraguas', undercover: 'Sombrilla' },
    { normal: 'French y Beruti', undercover: 'Repartidores' }, // Repartían cintas
    { normal: 'Constitución', undercover: 'Papel' },
    { normal: 'Malvinas', undercover: 'Islas' },
    { normal: 'Perón', undercover: 'General' },
    { normal: 'Evita', undercover: 'Actriz' },
    { normal: 'Granadero', undercover: 'Portero' }, // Por estar parados
    { normal: 'Cabildo Abierto', undercover: 'Reunión de Consorcio' },
    { normal: 'Independencia', undercover: 'Divorcio' },
    { normal: 'Revolución', undercover: 'Quilombo' },
    { normal: 'Patria', undercover: 'Tierra' },
    { normal: 'Prócer', undercover: 'Estatua' },
    { normal: 'Combate', undercover: 'Pelea' },
    { normal: 'Historia', undercover: 'Cuento' },
  ],
  religion: [
    { normal: 'Dios', undercover: 'Messi' },
    { normal: 'Infierno', undercover: 'Verano' },
    { normal: 'Cielo', undercover: 'Techo' },
    { normal: 'Diablo', undercover: 'Político' },
    { normal: 'Biblia', undercover: 'Libro' },
    { normal: 'Misa', undercover: 'Reunión' },
    { normal: 'Cura', undercover: 'Psicólogo' },
    { normal: 'Papa', undercover: 'Rey' },
    { normal: 'Monja', undercover: 'Enfermera' },
    { normal: 'Pecado', undercover: 'Error' },
    { normal: 'Milagro', undercover: 'Suerte' },
    { normal: 'Iglesia', undercover: 'Castillo' },
    { normal: 'Navidad', undercover: 'Cumpleaños' },
    { normal: 'Adán y Eva', undercover: 'Los Pimpinela' },
    { normal: 'Mandamientos', undercover: 'Reglas' },
    { normal: 'Ángel', undercover: 'Fantasma' },
    { normal: 'Rezar', undercover: 'Pedir' },
    { normal: 'Cruz', undercover: 'Espada' },
    { normal: 'Alma', undercover: 'Sombra' },
    { normal: 'Bautismo', undercover: 'Baño' },
    { normal: 'Casamiento', undercover: 'Funeral' },
    { normal: 'Confesión', undercover: 'Chisme' },
    { normal: 'Paraíso', undercover: 'Playa' },
    { normal: 'Demonio', undercover: 'Suegra' },
    { normal: 'Rosario', undercover: 'Collar' },
    { normal: 'Santo', undercover: 'Estatua' },
    { normal: 'Fe', undercover: 'Esperanza' },
    { normal: 'Templo', undercover: 'Cine' },
    { normal: 'Ofrenda', undercover: 'Propina' },
    { normal: 'Profeta', undercover: 'Mentiroso' },
    { normal: 'Apocalipsis', undercover: 'Fin de Mes' },
    { normal: 'Arca de Noé', undercover: 'Zoológico' },
    { normal: 'Moisés', undercover: 'Aquaman' },
    { normal: 'Jesús', undercover: 'Hippie' },
    { normal: 'Judas', undercover: 'Amigo' },
    { normal: 'Ateo', undercover: 'Ciego' },
    { normal: 'Religión', undercover: 'Fútbol' },
    { normal: 'Culto', undercover: 'Fan Club' },
    { normal: 'Espíritu', undercover: 'Viento' },
    { normal: 'Resurrección', undercover: 'Siesta' },
    { normal: 'Génesis', undercover: 'Principio' },
    { normal: 'Pastor', undercover: 'Vendedor' },
    { normal: 'Monaguillo', undercover: 'Ayudante' },
    { normal: 'Vaticano', undercover: 'Shopping' },
    { normal: 'Agua Bendita', undercover: 'Alcohol' },
    { normal: 'Hostia', undercover: 'Galletita' },
    { normal: 'Cuaresma', undercover: 'Dieta' },
  ],
  cordoba: [
    { normal: 'Fernet', undercover: 'Jarabe' },
    { normal: 'Pritty', undercover: 'Limonada' },
    { normal: 'La Mona Jiménez', undercover: 'Tarzán' },
    { normal: 'Sierras', undercover: 'Montaña Rusa' },
    { normal: 'Choripán', undercover: 'Pancho' },
    { normal: 'La Cañada', undercover: 'Zanja' },
    { normal: 'Alfajor', undercover: 'Sándwich' },
    { normal: 'Cuarteto', undercover: 'Ruido' },
    { normal: 'Arco de Córdoba', undercover: 'Puente' },
    { normal: 'Culia', undercover: 'Hermano' },
    { normal: 'Bondi', undercover: 'Lancha' },
    { normal: 'Bailazo', undercover: 'Gimnasio' },
    { normal: 'Talleres', undercover: 'Mecánico' },
    { normal: 'Dique', undercover: 'Pared' },
    { normal: 'Cabrito', undercover: 'Perro' },
    { normal: 'Gato', undercover: 'Peluca' },
    { normal: 'Vino', undercover: 'Agua' },
    { normal: 'Joda', undercover: 'Trabajo' },
    { normal: 'Asado', undercover: 'Quema' },
    { normal: 'Rio', undercover: 'Barro' },
    { normal: 'Carlos Paz', undercover: 'Las Vegas' },
    { normal: 'Peperina', undercover: 'Pasto' },
    { normal: 'Mate', undercover: 'Sopa' },
    { normal: 'Birra', undercover: 'Té' },
    { normal: 'Barrio', undercover: 'Villa' },
    { normal: 'Centro', undercover: 'Hormiguero' },
    { normal: 'Calor', undercover: 'Horno' },
    { normal: 'Mosquito', undercover: 'Avión' },
    { normal: 'Siesta', undercover: 'Muerte' },
    { normal: 'Empanada', undercover: 'Raviol' },
    { normal: 'Festival', undercover: 'Desfile' },
    { normal: 'Cosquín', undercover: 'Woodstock' },
    { normal: 'Jesús María', undercover: 'Rodeo' },
    { normal: 'Rally', undercover: 'Choque' },
    { normal: 'Estudiantes', undercover: 'Vagos' },
    { normal: 'Nueva Córdoba', undercover: 'Pasarela' },
    { normal: 'Güemes', undercover: 'Hipster' },
    { normal: 'Conigiglio', undercover: 'Helado' },
    { normal: 'Caño', undercover: 'Tubo' },
    { normal: 'Lomito', undercover: 'Hamburguesa' },
    { normal: 'Música', undercover: 'Gritos' },
    { normal: 'Amigo', undercover: 'Desconocido' },
    { normal: 'Insulto', undercover: 'Saludo' },
    { normal: 'Tonada', undercover: 'Canto' },
    { normal: 'Chiste', undercover: 'Mentira' },
    // Nuevos
    { normal: 'Jarra', undercover: 'Vaso' },
    { normal: 'Hielo', undercover: 'Piedra' },
    { normal: 'Embalse', undercover: 'Pileta' },
    { normal: 'Burro', undercover: 'Caballo' },
    { normal: 'Tunga Tunga', undercover: 'Música' },
    { normal: 'Caravana', undercover: 'Excursión' },
    { normal: 'Cucú', undercover: 'Pájaro' },
    { normal: 'Sargento Cabral', undercover: 'Estadio' },
    { normal: 'Pati', undercover: 'Hamburguesa' },
    { normal: 'Criollito', undercover: 'Pan' },
    { normal: 'Costanera', undercover: 'Rambla' },
    { normal: 'Kempes', undercover: 'Cancha' },
    { normal: 'Instituto', undercover: 'Colegio' },
    { normal: 'Racing', undercover: 'Carrera' },
    { normal: 'Chateau', undercover: 'Castillo' },
    { normal: 'Paseo del Buen Pastor', undercover: 'Iglesia' },
    { normal: 'Cerro de las Rosas', undercover: 'Jardín' },
    { normal: 'Villa Warcalde', undercover: 'Campo' },
    { normal: 'Feriar', undercover: 'Mercado' },
    { normal: 'Tropezón', undercover: 'Caída' },
    //Mas palabras graciosas de memes de internet
    {normal: 'Chupetón', undercover: 'Chupete'},
    {normal: 'No es coca papi', undercover: 'Coca-Cola'},
  ],
  argentina: [
    { normal: 'Mate', undercover: 'Pasto' },
    { normal: 'Asado', undercover: 'Reunión' },
    { normal: 'Dulce de Leche', undercover: 'Barro' },
    { normal: 'Obelisco', undercover: 'Agujas' },
    { normal: 'Tango', undercover: 'Pelea' },
    { normal: 'Inflación', undercover: 'Globo' },
    { normal: 'Piquete', undercover: 'Fiesta' },
    { normal: 'Grieta', undercover: 'Pozo' },
    { normal: 'Dólar', undercover: 'Lechuga' },
    { normal: 'Subte', undercover: 'Cueva' },
    { normal: 'Colectivo', undercover: 'Ganado' },
    { normal: 'Kiosco', undercover: 'Banco' },
    { normal: 'Aguinaldo', undercover: 'Mito' },
    { normal: 'Jubilación', undercover: 'Hambre' },
    { normal: 'Truco', undercover: 'Trampa' },
    { normal: 'Gaucho', undercover: 'Hipster' },
    { normal: 'Fútbol', undercover: 'Religión' },
    { normal: 'Maradona', undercover: 'Dios' },
    { normal: 'Político', undercover: 'Payaso' },
    { normal: 'Sindicato', undercover: 'Mafia' },
    { normal: 'Paro', undercover: 'Feriado' },
    { normal: 'Cacerolazo', undercover: 'Concierto' },
    { normal: 'Choripán', undercover: 'Hot Dog' },
    { normal: 'Empanada', undercover: 'Tarta' },
    { normal: 'Milanesa', undercover: 'Bife' },
    { normal: 'Malbec', undercover: 'Vinagre' },
    { normal: 'Glaciar', undercover: 'Hielo' },
    { normal: 'Cataratas', undercover: 'Ducha' },
    { normal: 'Aconcagua', undercover: 'Piedra' },
    { normal: 'Ruta 40', undercover: 'Camino' },
    { normal: 'Costa', undercover: 'Pelopincho' },
    { normal: 'Nieve', undercover: 'Telgopor' },
    { normal: 'Pingüino', undercover: 'Mozo' },
    { normal: 'Carpincho', undercover: 'Rata' },
    { normal: 'Hornero', undercover: 'Albañil' },
    { normal: 'Cóndor', undercover: 'Paloma' },
    { normal: 'Cheto', undercover: 'Rico' },
    { normal: 'Turro', undercover: 'Picante' },
    { normal: 'Chamuyo', undercover: 'Poesía' },
    { normal: 'Boludo', undercover: 'Genio' },
    { normal: 'Mufa', undercover: 'Bruja' },
    { normal: 'Cábala', undercover: 'Locura' },
    { normal: 'Finde Largo', undercover: 'Vacaciones' },
    { normal: 'Sube', undercover: 'Tarjeta' },
    { normal: 'Plaza', undercover: 'Baño' },
    { normal: 'Perro', undercover: 'Hijo' },
    // Nuevos
    { normal: 'Casa Rosada', undercover: 'Castillo' },
    { normal: 'Pampa', undercover: 'Cancha' },
    { normal: 'Poncho', undercover: 'Sábana' },
    { normal: 'Yaguareté', undercover: 'Gato' },
    { normal: '9 de Julio', undercover: 'Pista' },
    { normal: 'Guiso', undercover: 'Sopa' },
    { normal: 'Mantecol', undercover: 'Jabón' },
    { normal: 'Tereré', undercover: 'Jugo' },
    { normal: 'Fainá', undercover: 'Pizza' },
    { normal: 'Birome', undercover: 'Lápiz' },
    { normal: 'Bondiola', undercover: 'Jamón' },
    { normal: 'Picada', undercover: 'Cena' },
    { normal: 'Soda', undercover: 'Agua con Gas' },
    { normal: 'Chocotorta', undercover: 'Tiramisú' },
    { normal: 'Toripollo', undercover: 'Engendro' }, // Clásico meme/comida ruta
    { normal: 'Alambre', undercover: 'Hilo' }, // Lo atamo con alambre
    { normal: 'Flete', undercover: 'Mudanza' },
    { normal: 'Prode', undercover: 'Lotería' },
    { normal: 'Quini 6', undercover: 'Jubilación' },
    { normal: 'Campera', undercover: 'Buzo' },
  ],
  farandula: [
    { normal: 'Vedette', undercover: 'Plumero' },
    { normal: 'Chimento', undercover: 'Noticia' },
    { normal: 'Escándalo', undercover: 'Show' },
    { normal: 'Reality', undercover: 'Zoológico' },
    { normal: 'Canje', undercover: 'Robo' },
    { normal: 'Influencer', undercover: 'Vago' },
    { normal: 'Divorcio', undercover: 'Negocio' },
    { normal: 'Panelista', undercover: 'Cotorra' },
    { normal: 'Exclusiva', undercover: 'Mentira' },
    { normal: 'Verano', undercover: 'Desnudez' },
    { normal: 'Jurado', undercover: 'Verdugo' },
    { normal: 'Rating', undercover: 'Dinero' },
    { normal: 'Paparazzi', undercover: 'Mosquito' },
    { normal: 'Botox', undercover: 'Plástico' },
    { normal: 'Cirugía', undercover: 'Photoshop' },
    { normal: 'Romance', undercover: 'Contrato' },
    { normal: 'Cuernos', undercover: 'Adorno' },
    { normal: 'Boda', undercover: 'Fiesta' },
    { normal: 'Separación', undercover: 'Prensa' },
    { normal: 'Bailando', undercover: 'Peleando' },
    { normal: 'Cantando', undercover: 'Gritando' },
    { normal: 'Famoso', undercover: 'Desconocido' },
    { normal: 'Modelo', undercover: 'Maniquí' },
    { normal: 'Actor', undercover: 'Mentiroso' },
    { normal: 'Conductor', undercover: 'Chofer' },
    { normal: 'Diva', undercover: 'Abuela' },
    { normal: 'Mediático', undercover: 'Payaso' },
    { normal: 'Redes', undercover: 'Trampa' },
    { normal: 'Foto', undercover: 'Espejo' },
    { normal: 'Video', undercover: 'Prueba' },
    { normal: 'Audio', undercover: 'Viral' },
    { normal: 'Twitter', undercover: 'Cloaca' },
    { normal: 'Instagram', undercover: 'Vidriera' },
    { normal: 'TikTok', undercover: 'Baile' },
    { normal: 'Televisión', undercover: 'Basura' },
    { normal: 'Revista', undercover: 'Papel' },
    { normal: 'Microfono', undercover: 'Arma' },
    { normal: 'Cámara', undercover: 'Ojo' },
    { normal: 'Alfombra Roja', undercover: 'Vereda' },
    { normal: 'Premio', undercover: 'Juguete' },
    { normal: 'Fiesta', undercover: 'Trabajo' },
    { normal: 'Fans', undercover: 'Zombies' },
    { normal: 'Ego', undercover: 'Globo' },
  ],
  comida: [
    { normal: 'Milanesa', undercover: 'Zapato' },
    { normal: 'Pizza', undercover: 'Rueda' },
    { normal: 'Locro', undercover: 'Vómito' }, // Por el aspecto
    { normal: 'Empanada', undercover: 'Sobre' },
    { normal: 'Flan', undercover: 'Gelatina' },
    { normal: 'Sifón', undercover: 'Extintor' },
    { normal: 'Vino', undercover: 'Sangre' },
    { normal: 'Sorrentinos', undercover: 'Ovnis' },
    { normal: 'Molleja', undercover: 'Grasa' },
    { normal: 'Morcilla', undercover: 'Carbón' },
    { normal: 'Papas Fritas', undercover: 'Palitos' },
    { normal: 'Fideos', undercover: 'Gusanos' },
    { normal: 'Tuco', undercover: 'Sangre' },
    { normal: 'Queso', undercover: 'Plástico' },
    { normal: 'Pan', undercover: 'Esponja' },
    { normal: 'Facturas', undercover: 'Papeles' },
    { normal: 'Medialuna', undercover: 'Banana' },
    { normal: 'Churros', undercover: 'Caños' },
    { normal: 'Pastel', undercover: 'Ladrillo' },
    { normal: 'Torta', undercover: 'Mentira' },
    { normal: 'Helado', undercover: 'Crema' },
    { normal: 'Chocolate', undercover: 'Tierra' },
    { normal: 'Caramelo', undercover: 'Diente' },
    { normal: 'Chicle', undercover: 'Suela' },
    { normal: 'Agua', undercover: 'Vodka' },
    { normal: 'Cerveza', undercover: 'Pis' }, // Chiste clásico
    { normal: 'Café', undercover: 'Petróleo' },
    { normal: 'Leche', undercover: 'Pintura' },
    { normal: 'Huevo', undercover: 'Pelota' },
    { normal: 'Pollo', undercover: 'Pájaro' },
    { normal: 'Vaca', undercover: 'Perro' },
    { normal: 'Cerdo', undercover: 'Policía' },
    { normal: 'Pescado', undercover: 'Sirena' },
    { normal: 'Sushi', undercover: 'Carnada' },
    { normal: 'Ensalada', undercover: 'Pasto' },
    { normal: 'Tomate', undercover: 'Manzana' },
    { normal: 'Papa', undercover: 'Piedra' },
    { normal: 'Zapallo', undercover: 'Cabeza' },
    { normal: 'Ajo', undercover: 'Vampiro' },
    { normal: 'Cebolla', undercover: 'Llanto' },
    { normal: 'Sal', undercover: 'Arena' },
  ],
  futbol: [
    { normal: 'Gol', undercover: 'Beso' },
    { normal: 'Árbitro', undercover: 'Ladrón' },
    { normal: 'Offside', undercover: 'Adelanto' },
    { normal: 'Hincha', undercover: 'Barrabrava' },
    { normal: 'Mundial', undercover: 'Guerra' },
    { normal: 'Descenso', undercover: 'Infierno' },
    { normal: 'Clásico', undercover: 'Final' },
    { normal: 'Pelota', undercover: 'Melón' },
    { normal: 'DT', undercover: 'Padre' },
    { normal: 'Arquero', undercover: 'Manos' },
    { normal: 'Var', undercover: 'Cine' },
    { normal: 'Cancha', undercover: 'Potrero' },
    { normal: 'Césped', undercover: 'Alfombra' },
    { normal: 'Tribuna', undercover: 'Jaula' },
    { normal: 'Bandera', undercover: 'Trapo' },
    { normal: 'Camiseta', undercover: 'Piel' },
    { normal: 'Botines', undercover: 'Zapatillas' },
    { normal: 'Tarjeta Roja', undercover: 'Sangre' },
    { normal: 'Penal', undercover: 'Suerte' },
    { normal: 'Corner', undercover: 'Esquina' },
    { normal: 'Barrera', undercover: 'Pared' },
    { normal: 'Caño', undercover: 'Túnel' },
    { normal: 'Chilena', undercover: 'Tijera' },
    { normal: 'Paloma', undercover: 'Vuelo' },
    { normal: 'Mano', undercover: 'Pie' },
    { normal: 'Falta', undercover: 'Golpe' },
    { normal: 'Simular', undercover: 'Actuar' },
    { normal: 'Lesión', undercover: 'Descanso' },
    { normal: 'Camilla', undercover: 'Cama' },
    { normal: 'Vestuario', undercover: 'Baño' },
    { normal: 'Ducha', undercover: 'Lluvia' },
    { normal: 'Trofeo', undercover: 'Jarrón' },
    { normal: 'Medalla', undercover: 'Moneda' },
    { normal: 'Campeón', undercover: 'Rey' },
    { normal: 'Perdedor', undercover: 'Llorón' },
    { normal: 'Empate', undercover: 'Nada' },
    { normal: 'Alargue', undercover: 'Tortura' },
    { normal: 'Penales', undercover: 'Lotería' },
    { normal: 'Relator', undercover: 'Loco' },
    { normal: 'Periodista', undercover: 'Buitre' },
    { normal: 'Contrato', undercover: 'Papel' },
  ],
  marcas: [
    { normal: 'Manaos', undercover: 'Veneno' },
    { normal: 'Marolio', undercover: 'Aceite' },
    { normal: 'Piturro', undercover: 'Cartón' },
    { normal: 'Coca Cola', undercover: 'Petróleo' },
    { normal: 'Guaymallén', undercover: 'Caviar' },
    { normal: 'Cindor', undercover: 'Barro' },
    { normal: 'Termo', undercover: 'Cabeza' },
    { normal: 'Quilmes', undercover: 'Agua' },
    { normal: 'Flybondi', undercover: 'Colectivo' },
    { normal: 'Mercado Libre', undercover: 'Correo' },
    { normal: 'McDonalds', undercover: 'Plástico' },
    { normal: 'Burger King', undercover: 'Carbón' },
    { normal: 'Starbucks', undercover: 'Agua Sucia' },
    { normal: 'iPhone', undercover: 'Ladrillo' },
    { normal: 'Samsung', undercover: 'Bomba' }, // Referencia explosiva vieja
    { normal: 'Windows', undercover: 'Ventana' },
    { normal: 'Netflix', undercover: 'Sillón' },
    { normal: 'Spotify', undercover: 'Radio' },
    { normal: 'Uber', undercover: 'Remís' },
    { normal: 'Rappi', undercover: 'Moto' },
    { normal: 'PedidosYa', undercover: 'Hambre' },
    { normal: 'Facebook', undercover: 'Geriátrico' },
    { normal: 'Nike', undercover: 'Pipa' },
    { normal: 'Adidas', undercover: 'Rayas' },
    { normal: 'Puma', undercover: 'Gato' },
    { normal: 'Ford', undercover: 'Tortuga' },
    { normal: 'Ferrari', undercover: 'Cohete' },
    { normal: 'Toyota', undercover: 'Tanque' },
    { normal: 'Fiat', undercover: 'Fitito' },
    { normal: 'Bic', undercover: 'Pluma' },
    { normal: 'Gillette', undercover: 'Cuchillo' },
    { normal: 'Colgate', undercover: 'Jabón' },
    { normal: 'Rexona', undercover: 'Perfume' },
    { normal: 'Dove', undercover: 'Crema' },
    { normal: 'Serenísima', undercover: 'Agua' },
    { normal: 'Arcor', undercover: 'Dulce' },
    { normal: 'Bagley', undercover: 'Desayuno' },
    { normal: 'Brahma', undercover: 'Pis' },
    { normal: 'Fernet Branca', undercover: 'Dios' },
    { normal: 'Playstation', undercover: 'Juguete' },
  ],
  musica: [
    { normal: 'Rock', undercover: 'Ruido' },
    { normal: 'Cumbia', undercover: 'Alcohol' },
    { normal: 'Recital', undercover: 'Misa' },
    { normal: 'Pogo', undercover: 'Pelea' },
    { normal: 'Guitarra', undercover: 'Palo' },
    { normal: 'Batería', undercover: 'Ollas' },
    { normal: 'Cantante', undercover: 'Grito' },
    { normal: 'Autotune', undercover: 'Robot' },
    { normal: 'Trap', undercover: 'Balbuceo' },
    { normal: 'Reggaeton', undercover: 'Sexo' },
    { normal: 'Pop', undercover: 'Chicle' },
    { normal: 'Jazz', undercover: 'Aburrido' },
    { normal: 'Clásica', undercover: 'Sueño' },
    { normal: 'Tango', undercover: 'Tristeza' },
    { normal: 'Folklore', undercover: 'Campo' },
    { normal: 'Electrónica', undercover: 'Computadora' },
    { normal: 'Piano', undercover: 'Mesa' },
    { normal: 'Violín', undercover: 'Gato' },
    { normal: 'Trompeta', undercover: 'Elefante' },
    { normal: 'Bajo', undercover: 'Guitarra' }, // Confusión común
    { normal: 'Micrófono', undercover: 'Helado' },
    { normal: 'Parlante', undercover: 'Caja' },
    { normal: 'Auriculares', undercover: 'Orejeras' },
    { normal: 'Disco', undercover: 'Pizza' },
    { normal: 'Spotify', undercover: 'Radio' },
    { normal: 'Youtube', undercover: 'Tele' },
    { normal: 'Video', undercover: 'Pelicula' },
    { normal: 'Baile', undercover: 'Gimnasia' },
    { normal: 'Coreografía', undercover: 'Desorden' },
    { normal: 'Karaoke', undercover: 'Vergüenza' },
    { normal: 'DJ', undercover: 'Ipoder' },
    { normal: 'Banda', undercover: 'Pandilla' },
    { normal: 'Solista', undercover: 'Solo' },
    { normal: 'Fan', undercover: 'Loca' },
    { normal: 'Escenario', undercover: 'Tarima' },
    { normal: 'Luces', undercover: 'Sol' },
    { normal: 'Humo', undercover: 'Niebla' },
    { normal: 'Entrada', undercover: 'Papel' },
    { normal: 'Valla', undercover: 'Reja' },
  ],
  lugares: [
    { normal: 'Telo', undercover: 'Oficina' },
    { normal: 'Playa', undercover: 'Arenero' },
    { normal: 'Cine', undercover: 'Cueva' },
    { normal: 'Gimnasio', undercover: 'Tortura' },
    { normal: 'Hospital', undercover: 'Mecánico' },
    { normal: 'Comisaría', undercover: 'Zoológico' },
    { normal: 'Aeropuerto', undercover: 'Shopping' },
    { normal: 'Boliche', undercover: 'Lata' },
    { normal: 'Cementerio', undercover: 'Jardín' },
    { normal: 'Zoológico', undercover: 'Cárcel' },
    { normal: 'Motel', undercover: 'Hotel' },
    { normal: 'Escuela', undercover: 'Cárcel' },
    { normal: 'Universidad', undercover: 'Laberinto' },
    { normal: 'Oficina', undercover: 'Jaula' },
    { normal: 'Banco', undercover: 'Cola' },
    { normal: 'Supermercado', undercover: 'Despensa' },
    { normal: 'Shopping', undercover: 'Aire Acondicionado' },
    { normal: 'Kiosco', undercover: 'Ventana' },
    { normal: 'Farmacia', undercover: 'Droguería' },
    { normal: 'Carnicería', undercover: 'Morgue' },
    { normal: 'Panadería', undercover: 'Horno' },
    { normal: 'Verdulería', undercover: 'Selva' },
    { normal: 'Plaza', undercover: 'Baño' },
    { normal: 'Parque', undercover: 'Bosque' },
    { normal: 'Calle', undercover: 'Río' }, // Cuando llueve
    { normal: 'Vereda', undercover: 'Piso' },
    { normal: 'Ruta', undercover: 'Pista' },
    { normal: 'Puente', undercover: 'Tunel' },
    { normal: 'Edificio', undercover: 'Caja' },
    { normal: 'Casa', undercover: 'Cueva' },
    { normal: 'Departamento', undercover: 'Caja de Zapatos' },
    { normal: 'Baño', undercover: 'Trono' },
    { normal: 'Cocina', undercover: 'Laboratorio' },
    { normal: 'Habitación', undercover: 'Cueva' },
    { normal: 'Patio', undercover: 'Baldío' },
    { normal: 'Techo', undercover: 'Cielo' },
    { normal: 'Piso', undercover: 'Suelo' },
    { normal: 'Pared', undercover: 'Muro' },
    { normal: 'Ventana', undercover: 'Pantalla' },
    { normal: 'Puerta', undercover: 'Boca' },
    { normal: 'Ascensor', undercover: 'Caja' },
  ],
  objetos: [
    { normal: 'Heladera', undercover: 'Invierno' },
    { normal: 'Lavarropas', undercover: 'Torbellino' },
    { normal: 'Televisor', undercover: 'Espejo' },
    { normal: 'Cama', undercover: 'Nube' },
    { normal: 'Inodoro', undercover: 'Silla' },
    { normal: 'Tenedor', undercover: 'Tridente' },
    { normal: 'Vaso', undercover: 'Balde' },
    { normal: 'Puerta', undercover: 'Tabla' },
    { normal: 'Llave', undercover: 'Fierro' },
    { normal: 'Almohada', undercover: 'Bolsa' },
    { normal: 'Cuchillo', undercover: 'Espada' },
    { normal: 'Cuchara', undercover: 'Pala' },
    { normal: 'Plato', undercover: 'Disco' },
    { normal: 'Olla', undercover: 'Casco' },
    { normal: 'Sartén', undercover: 'Raqueta' },
    { normal: 'Microondas', undercover: 'Tele' },
    { normal: 'Horno', undercover: 'Infierno' },
    { normal: 'Mesa', undercover: 'Plataforma' },
    { normal: 'Silla', undercover: 'Trono' },
    { normal: 'Sillón', undercover: 'Cama' },
    { normal: 'Lámpara', undercover: 'Sol' },
    { normal: 'Foco', undercover: 'Idea' },
    { normal: 'Enchufe', undercover: 'Nariz' },
    { normal: 'Cable', undercover: 'Serpiente' },
    { normal: 'Control Remoto', undercover: 'Poder' },
    { normal: 'Celular', undercover: 'Mano' },
    { normal: 'Cargador', undercover: 'Vida' },
    { normal: 'Computadora', undercover: 'Cerebro' },
    { normal: 'Teclado', undercover: 'Piano' },
    { normal: 'Mouse', undercover: 'Rata' },
    { normal: 'Pantalla', undercover: 'Ventana' },
    { normal: 'Reloj', undercover: 'Tiempo' },
    { normal: 'Espejo', undercover: 'Gemelo' },
    { normal: 'Toalla', undercover: 'Trapo' },
    { normal: 'Jabón', undercover: 'Piedra' },
    { normal: 'Shampoo', undercover: 'Baba' },
    { normal: 'Papel Higiénico', undercover: 'Lija' },
    { normal: 'Cepillo', undercover: 'Escoba' },
    { normal: 'Pasta Dental', undercover: 'Crema' },
    { normal: 'Perfume', undercover: 'Veneno' },
  ]
};

export const MIN_PLAYERS = 3;
export const DEFAULT_TIMER_SECONDS = 300;