import { ThemeOption, WordPair } from './types';

export const THEMES: ThemeOption[] = [
  { id: 'argentina', label: 'Argentinidad al Palo', emoji: '🇦🇷' },
  { id: 'cordoba', label: 'Córdoba Básica', emoji: '🍷' },
  { id: 'comida', label: 'Comida de Bodegón', emoji: '🍕' },
  { id: 'farandula', label: 'Farándula TV', emoji: '📺' },
  { id: 'futbol', label: 'Fútbol Pasión', emoji: '⚽' },
  { id: 'marcas', label: 'Marcas Nostalgia', emoji: '🏷️' },
  { id: 'musica', label: 'Rock & Cumbia', emoji: '🎸' },
  { id: 'lugares', label: 'Lugares & Viajes', emoji: '✈️' },
  { id: 'objetos', label: 'Cosas de la Casa', emoji: '🏠' },
];

export const WORD_LISTS: Record<string, WordPair[]> = {
  cordoba: [
    { normal: 'Fernet', undercover: 'Gancia' },
    { normal: 'La Mona Jiménez', undercover: 'Rodrigo' },
    { normal: 'Choripán', undercover: 'Pancho' },
    { normal: 'Patio Olmos', undercover: 'Nuevocentro' },
    { normal: 'Carlos Paz', undercover: 'Mar del Plata' },
    { normal: 'Talleres', undercover: 'Belgrano' },
    { normal: 'Pritty', undercover: 'Manaos' },
    { normal: 'Cuarteto', undercover: 'Cumbia' },
    { normal: 'Bondi', undercover: 'Taxi' },
    { normal: 'Sargento Cabral', undercover: 'Estadio del Centro' },
    { normal: 'La Cañada', undercover: 'Río Suquía' },
    { normal: 'Culia', undercover: 'Boludo' },
    { normal: 'Arco de Córdoba', undercover: 'Mujer Urbana' },
    { normal: 'Parque Sarmiento', undercover: 'Parque de las Naciones' },
    { normal: 'Buen Pastor', undercover: 'Paseo del Jockey' },
    { normal: 'Cosquín Rock', undercover: 'Jesús María' },
    { normal: 'Piñón Fijo', undercover: 'Sapo Pepe' },
    { normal: 'Instituto', undercover: 'Racing de Córdoba' },
    { normal: 'Barrio General Paz', undercover: 'Nueva Córdoba' },
    { normal: 'Costanera', undercover: 'Circunvalación' },
    { normal: 'Alfajor Cordobés', undercover: 'Colación' },
    { normal: 'Peperina', undercover: 'Menta' },
    { normal: 'Dique San Roque', undercover: 'Embalse' },
    { normal: 'Cerro Uritorco', undercover: 'Champaquí' },
    { normal: 'Villa General Belgrano', undercover: 'La Cumbrecita' },
    { normal: 'Feriar', undercover: 'Orfeo' },
    { normal: 'Universidad Nacional (UNC)', undercover: 'Siglo 21' },
    { normal: 'Mestizo', undercover: 'Juez' },
    { normal: 'Schiaretti', undercover: 'De la Sota' },
  ],
  argentina: [
    { normal: 'Obelisco', undercover: 'Cabildo' },
    { normal: 'Messi', undercover: 'Maradona' },
    { normal: 'Dólar Blue', undercover: 'Dólar Oficial' },
    { normal: 'Cumbia', undercover: 'Cuarteto' },
    { normal: 'Truco', undercover: 'Chinchón' },
    { normal: 'Mate', undercover: 'Tereré' },
    { normal: 'Dulce de Leche', undercover: 'Membrillo' },
    { normal: 'Asado', undercover: 'Parillada' },
    { normal: 'Tango', undercover: 'Folklore' },
    { normal: 'Malvinas', undercover: 'Antártida' },
    { normal: 'Cataratas del Iguazú', undercover: 'Glaciar Perito Moreno' },
    { normal: 'Bariloche', undercover: 'San Martín de los Andes' },
    { normal: 'Subte', undercover: 'Tren' },
    { normal: 'DNI', undercover: 'Pasaporte' },
    { normal: 'Aguinaldo', undercover: 'Sueldo' },
    { normal: 'Favaloro', undercover: 'Houssay' },
    { normal: 'Gardel', undercover: 'Goyeneche' },
    { normal: 'Mafalda', undercover: 'Clemente' },
    { normal: 'Martin Fierro', undercover: 'Don Quijote' },
    { normal: '9 de Julio', undercover: '25 de Mayo' },
    { normal: 'Casa Rosada', undercover: 'Congreso' },
    { normal: 'Peso Argentino', undercover: 'Dólar Blue' },
    { normal: 'Pato', undercover: 'Polo' },
    { normal: 'Hornero', undercover: 'Cóndor' },
    { normal: 'Ceibo', undercover: 'Jacarandá' },
    { normal: 'Che', undercover: 'Vos' },
    { normal: 'Boludo', undercover: 'Pelotudo' },
    { normal: 'Colectivo', undercover: 'Remís' },
    { normal: 'Kiosco', undercover: 'Almacén' },
    { normal: 'Portero Eléctrico', undercover: 'Timbre' },
    { normal: 'Bidet', undercover: 'Inodoro' },
  ],
  comida: [
    { normal: 'Milanesa', undercover: 'Suprema' },
    { normal: 'Pizza', undercover: 'Empanada' },
    { normal: 'Locro', undercover: 'Guiso' },
    { normal: 'Humita', undercover: 'Tamal' },
    { normal: 'Alfajor', undercover: 'Conito' },
    { normal: 'Facturas', undercover: 'Bizcochitos' },
    { normal: 'Chocotorta', undercover: 'Tiramisú' },
    { normal: 'Sandwich de Miga', undercover: 'Tostado' },
    { normal: 'Picada', undercover: 'Asado' },
    { normal: 'Flan con dulce', undercover: 'Budín de pan' },
    { normal: 'Mate Cocido', undercover: 'Té' },
    { normal: 'Vitel Toné', undercover: 'Lengua a la Vinagreta' },
    { normal: 'Pastel de Papa', undercover: 'Pastel de Carne' },
    { normal: 'Provoleta', undercover: 'Muzzarella' },
    { normal: 'Matambre a la Pizza', undercover: 'Vacío' },
    { normal: 'Revuelto Gramajo', undercover: 'Omelette' },
    { normal: 'Churros', undercover: 'Bolas de Fraile' },
    { normal: 'Polenta', undercover: 'Puré' },
    { normal: 'Ñoquis', undercover: 'Fideos' },
    { normal: 'Sifón de Soda', undercover: 'Agua con gas' },
    { normal: 'Vino Tinto', undercover: 'Cerveza' },
    { normal: 'Tortas Fritas', undercover: 'Rosquitas' },
    { normal: 'Pan Dulce', undercover: 'Budín' },
    { normal: 'Garrapiñada', undercover: 'Turrón' },
    { normal: 'Puchero', undercover: 'Sopa' },
  ],
  farandula: [
    { normal: 'Susana Giménez', undercover: 'Moria Casán' },
    { normal: 'Marcelo Tinelli', undercover: 'Guido Kaczka' },
    { normal: 'Mirtha Legrand', undercover: 'Graciela Alfano' },
    { normal: 'Wanda Nara', undercover: 'China Suárez' },
    { normal: 'Ricardo Fort', undercover: 'Flavio Mendoza' },
    { normal: 'Darío Barassi', undercover: 'Santiago del Moro' },
    { normal: 'Yanina Latorre', undercover: 'Viviana Canosa' },
    { normal: 'Lali', undercover: 'Tini' },
    { normal: 'Bizarrap', undercover: 'Duki' },
    { normal: 'Carmen Barbieri', undercover: 'Nazarena Vélez' },
    { normal: 'Pampita', undercover: 'Nicole Neumann' },
    { normal: 'Marley', undercover: 'Lizy Tagliani' },
    { normal: 'Guillermo Francella', undercover: 'Ricardo Darín' },
    { normal: 'Adrián Suar', undercover: 'Pablo Codevilla' },
    { normal: 'Jorge Rial', undercover: 'Luis Ventura' },
    { normal: 'Charlotte Caniggia', undercover: 'Alex Caniggia' },
    { normal: 'Sol Pérez', undercover: 'Cinthia Fernández' },
    { normal: 'Beto Casella', undercover: 'Baby Etchecopar' },
    { normal: 'Gran Hermano', undercover: 'MasterChef' },
    { normal: 'Intrusos', undercover: 'LAM' },
  ],
  futbol: [
    { normal: 'Boca Juniors', undercover: 'River Plate' },
    { normal: 'La Bombonera', undercover: 'El Monumental' },
    { normal: 'Scaloni', undercover: 'Bilardo' },
    { normal: 'Dibu Martínez', undercover: 'Goycochea' },
    { normal: 'Kun Agüero', undercover: 'Pipita Higuaín' },
    { normal: 'Mundial 86', undercover: 'Qatar 2022' },
    { normal: 'Independiente', undercover: 'Racing' },
    { normal: 'San Lorenzo', undercover: 'Huracán' },
    { normal: 'Riquelme', undercover: 'Palermo' },
    { normal: 'Gallardo', undercover: 'Ramón Díaz' },
    { normal: 'Tevez', undercover: 'Mascherano' },
    { normal: 'Di María', undercover: 'Dybala' },
    { normal: 'Julián Álvarez', undercover: 'Lautaro Martínez' },
    { normal: 'Vélez', undercover: 'Ferro' },
    { normal: 'Copa Libertadores', undercover: 'Champions League' },
    { normal: 'AFA', undercover: 'FIFA' },
    { normal: 'Barrabrava', undercover: 'Hincha' },
    { normal: 'Descenso', undercover: 'Campeonato' },
    { normal: 'Var', undercover: 'Árbitro' },
    { normal: 'Penal', undercover: 'Tiro Libre' },
  ],
  marcas: [
    { normal: 'Manaos', undercover: 'Coca Cola' },
    { normal: 'Marolio', undercover: 'Arcor' },
    { normal: 'Piturro', undercover: 'Jorgito' },
    { normal: 'Cunnington', undercover: 'Secco' },
    { normal: 'Guaymallén', undercover: 'Capitán del Espacio' },
    { normal: 'Sancor Bebé', undercover: 'Serenísima' },
    { normal: 'Lumilagro', undercover: 'Stanley' },
    { normal: 'Taragüi', undercover: 'Playadito' },
    { normal: 'Quilmes', undercover: 'Brahma' },
    { normal: 'Flybondi', undercover: 'Aerolíneas' },
    { normal: 'Mercado Libre', undercover: 'Correo Argentino' },
    { normal: 'RapiPago', undercover: 'Pago Fácil' },
    { normal: 'Sube', undercover: 'Monedas' },
    { normal: 'Naranjú', undercover: 'Mielquitas' },
    { normal: 'Fulbito', undercover: 'Tita' },
    { normal: 'Rhodesia', undercover: 'Mantecol' },
  ],
  musica: [
    { normal: 'Charly García', undercover: 'Fito Páez' },
    { normal: 'Spinetta', undercover: 'Cerati' },
    { normal: 'Los Palmeras', undercover: 'Ráfaga' },
    { normal: 'Damas Gratis', undercover: 'Pibes Chorros' },
    { normal: 'Sandro', undercover: 'Palito Ortega' },
    { normal: 'Gilda', undercover: 'Karina' },
    { normal: 'La Renga', undercover: 'Los Piojos' },
    { normal: 'Soda Stereo', undercover: 'Patricio Rey' },
    { normal: 'Callejero Fino', undercover: 'L-Gante' },
    { normal: 'Mercedes Sosa', undercover: 'Atahualpa Yupanqui' },
    { normal: 'Cosquín Rock', undercover: 'Lollapalooza' },
    { normal: 'Tan Biónica', undercover: 'Miranda' },
    { normal: 'Divididos', undercover: 'Las Pelotas' },
    { normal: 'Calamaro', undercover: 'Vicentico' },
    { normal: 'Yerba Brava', undercover: 'Mala Fama' },
  ],
  lugares: [
    { normal: 'Playa', undercover: 'Pileta' },
    { normal: 'Cine', undercover: 'Teatro' },
    { normal: 'Shopping', undercover: 'Feria' },
    { normal: 'Gimnasio', undercover: 'Parque' },
    { normal: 'Hospital', undercover: 'Farmacia' },
    { normal: 'Escuela', undercover: 'Universidad' },
    { normal: 'Comisaría', undercover: 'Cárcel' },
    { normal: 'Aeropuerto', undercover: 'Terminal' },
    { normal: 'Boliche', undercover: 'Bar' },
    { normal: 'Cementerio', undercover: 'Iglesia' },
    { normal: 'Zoológico', undercover: 'Granja' },
    { normal: 'Museo', undercover: 'Biblioteca' },
    { normal: 'Hotel', undercover: 'Camping' },
  ],
  objetos: [
    { normal: 'Heladera', undercover: 'Freezer' },
    { normal: 'Lavarropas', undercover: 'Secarropas' },
    { normal: 'Televisor', undercover: 'Computadora' },
    { normal: 'Cama', undercover: 'Sofá' },
    { normal: 'Mesa', undercover: 'Escritorio' },
    { normal: 'Silla', undercover: 'Banquea' },
    { normal: 'Tenedor', undercover: 'Cuchara' },
    { normal: 'Plato', undercover: 'Fuente' },
    { normal: 'Vaso', undercover: 'Copa' },
    { normal: 'Espejo', undercover: 'Ventana' },
    { normal: 'Puerta', undercover: 'Portón' },
    { normal: 'Llave', undercover: 'Candado' },
    { normal: 'Almohada', undercover: 'Almohadón' },
    { normal: 'Toalla', undercover: 'Repasador' },
    { normal: 'Escoba', undercover: 'Secador' },
  ]
};

export const MIN_PLAYERS = 3;
export const DEFAULT_TIMER_SECONDS = 300;